[meta]
title="Learn how to Optimize Performance with TPCH 100"
description="""\
    This notebook will help you understand how you can take advantage of SingleStoreDB distributed capability using TPCH-100.
"""
icon="database"
tags=["performance", "benchmark", "tpch", "benchmark", "shardkey", "ingest"]
destinations=["spaces"]
