[meta]
title="Resume Evaluator"
description="""\
    Resume Evaluator using vectors stored in SingleStore to find sutiable resume for your job description, with Indexed ANN search.\
    """
icon="arrows-spin"
tags=["vectordb", "genai", "openai", "rag"]
destinations=["spaces"]
