[meta]
title = "Ingest data from Confluent Cloud (Kafka)"
description = """
    Provides step-by-step guidance on seamlessly ingesting data from Confluent Cloud (Kafka) to SingleStore Database using a robust pipeline. """
icon = "database"
tags = ["iot", "training", "kafka", "pipeline", "realtime"]
destinations = ["spaces"]
